name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install Appium driver
      run: npm install -g appium

    - name: Download and extract Android SDK
      uses: actions/download-artifact@v2
      with:
        name: android-sdk

    - name: Set up Android environment variables
      run: |
        echo "##[set-env name=ANDROID_HOME;]${{ github.workspace }}/android-sdk"
        echo "##[add-path]${{ github.workspace }}/android-sdk/platform-tools"
        echo "##[add-path]${{ github.workspace }}/android-sdk/tools"
        echo "##[add-path]${{ github.workspace }}/android-sdk/tools/bin"

    - name: Accept Android licenses
      run: yes | ${{ github.workspace }}/android-sdk/tools/bin/sdkmanager --licenses

    - name: Install Appium driver
      run: npm install appium

    - name: Start Android Emulator
      run: avdmanager create avd -n test -k "system-images;android-29;google_apis;x86_64" --force && emulator -avd test -no-audio -no-window &

    - name: Wait for Emulator to be ready
      run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

    - name: Start Appium Server
      run: appium &

    - name: Run tests
      run: adb devices
