name: Windows Remote Desktop with Ngrok

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
  RDP_USERNAME: root
  RDP_PASSWORD: root

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ngrok
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath .
          Set-Location -Path "ngrok-stable-windows-amd64"

      - name: Start Ngrok Tunnel
        run: |
          Start-Process -FilePath "ngrok.exe" -ArgumentList "authtoken $env:NGROK_API_KEY"
          Start-Process -FilePath "ngrok.exe" -ArgumentList "rdp 3389"

      - name: Start Windows Remote Desktop
        run: |
          mstsc /v:127.0.0.1:3389 /f /u:$env:RDP_USERNAME /p:$env:RDP_PASSWORD
