name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' # or 'adopt-openj9', 'amazon-corretto', 'azul-zulu', 'bellsoft', 'graalvm', 'openjdk', 'oracle', 'sap-machine'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: success

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14


    - name: Upload Android SDK artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-sdk
        path: ${{ github.workspace }}/android-sdk

    - name: Set up environment
      run: echo 'ANDROID_HOME=D:\a\expressjs-prisma\expressjs-prisma/android-sdk' >> $GITHUB_ENV
      shell: bash

    - name: Add to PATH
      run: echo 'PATH=D:\a\expressjs-prisma\expressjs-prisma/android-sdk/platform-tools;D:\a\expressjs-prisma\expressjs-prisma/android-sdk/tools;D:\a\expressjs-prisma\expressjs-prisma/android-sdk/tools/bin' >> $GITHUB_ENV
      shell: bash


    - name: Accept Android SDK licenses
      run: |
        $sdkManager = "D:\a\expressjs-prisma\expressjs-prisma\android-sdk\tools\bin\sdkmanager.bat"
        $licenses = "$($sdkManager) --licenses"
        $licenses | ForEach-Object {
          if ($_ -match "Accept\? \(y/N\)") {
            $_ = "y"
          }
          Write-Output $_
        } | Out-File -FilePath "licenses.txt" -Encoding ASCII
        cmd.exe /C "type licenses.txt | $sdkManager"
      shell: pwsh
      env:
        JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\11.0.21-9\x64
        ANDROID_HOME: D:\a\expressjs-prisma\expressjs-prisma\android-sdk
        PATH: D:\a\expressjs-prisma\expressjs-prisma\android-sdk\platform-tools;D:\a\expressjs-prisma\expressjs-prisma\android-sdk\tools;D:\a\expressjs-prisma\expressjs-prisma\android-sdk\tools\bin

    - name: Install dependencies
      run: npm install

    
    - name: Install Appium driver
      run: npm install -g appium

    - name: Start Android Emulator
      run: avdmanager create avd -n test -k "system-images;android-29;google_apis;x86_64" --force && emulator -avd test -no-audio -no-window &

    - name: Wait for Emulator to be ready
      run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

    - name: Start Appium Server
      run: appium &

    - name: Run tests
      run: adb devices
