name: Node.js CI with Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  status: {}
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Start HTTP server
        run: npm start &

      - name: Install ngrok
        run: |
          curl -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok

      - name: Connect server to ngrok
        run: |
          if [ -n "$NGROK_API_KEY" ]; then
            ./ngrok authtoken $NGROK_API_KEY
            ./ngrok http 3000 --log=stdout > ngrok.log &
          fi
          
      - name: Display ngrok tunnel URL
        run: cat ngrok.log

