name: Accept Android SDK licenses

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accept-licenses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Android SDK Platform-Tools
        run: |
          wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
          unzip platform-tools-latest-linux.zip -d $HOME/android-sdk
          echo 'export PATH=$HOME/android-sdk/platform-tools:$PATH' >> $HOME/.bashrc

      - name: Accept licenses
        run: |
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

      - name: Start Emulator
        run: |
          avdmanager create avd --name test-emulator --package "system-images;android-29;google_apis;x86_64"
          emulator -avd test-emulator -no-audio -no-window -gpu swiftshader_indirect

      - name: Install dependencies
        run: npm ci
