name: Node.js CI with Ngrok

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Start HTTP server
        run: npm start &

      - name: Install ngrok
        run: |
          curl -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok

      - name: Connect server to ngrok
        run: |
          if [ -n "$NGROK_API_KEY" ]; then
            ./ngrok authtoken $NGROK_API_KEY
            ./ngrok http 3000 --log=stdout > ngrok.log &
          fi
          
      - name: Display ngrok tunnel URL
        run: cat ngrok.log

      - name: Commit the logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "update Logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
      - name: Wait for ngrok tunnel URL
        run: |
          until grep -q "url:" ngrok.log; do
              sleep 1
          done

      - name: keep alive
        run: |
          while true; do
            sleep 1
          done
        
